version: '3.1'

services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        links:
            - mysql

    web:
        build: ./build/php
        ports:
            - 80:80
        volumes:
            - './src:/simple-login'
        links:
            - mysql
